title: Internet Safety
description: Teaching kids how to live safely in an constantly connected world.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: https://kristin-kronstain-brown.github.io/internet-safety

aux_links:
  Template Repository: https://github.com/kristin-kronstain-brown/internet-safety
